title: Podcast Title
subtitle: Podcast Subtitle
header_logo: s3link (150x150 image)
author: 'The Fellowship of the Incarnate Divine'
webmaster: 'Oliver Ayers'
url: http://www.URL.com/
itunes_subscribe_link: copyAndPasteItunesSubscribeLinkHere

markdown: kramdown
timezone: America/Los_Angeles

rss_path: /feed
rss_name: index.xml

# about page
about_bailey_pic: https://s3-us-west-1.amazonaws.com/www.survivorteamgo.com/about-bailey-photo.JPG
about_oliver_pic: https://s3-us-west-1.amazonaws.com/www.survivorteamgo.com/about-oliver-photo.JPG

# podcast metadata
podcast_copyright: 2019 FID Productions. All rights reserved.
podcast_title: 'Podcast Title' # as opposed to episode_title
podcast_creator: 'The Fellowship of the Incarnate Divine' # same as author
podcast_owner: 'FID Productions' # distinct from author i guess?
# min 1400x1400 max 3000x3000 (original is 2000x2000)
podcast_art: compressed art s3 link - 1500 by 1500 but small file size
podcast_email: podcastemail@gmail.com
# must use &amp; if the category or subcategory contains an ampersand (&)
itunes_category: 'iTunes Category' 
itunes_subcategory: 'iTunes Subcategory' # if applicable
itunes_explicit: 'yes' # contains cursing (or adult content)
podcast_description: 'Podcast description - short'
podcast_summary: 'Podcast summary - longer'
podcast_subtitle: 'Podcast subtitle - very short'

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      # site specific
      layout: 'episode'
      # iTunes podcast metadata
      author: 'The Fellowship of the Incarnate Divine'
      artist: 'The Fellowship of the Incarnate Divine' # artist or host
      voices: ['Host1 Name', 'Host2 Name'] # overridden on episodes with guests
      copyright: '2019 FID Productions. All rights reserved.' # ???
      website: http://www.URL.com/

